version: '3'
services:
  redis:
    image: redis
    container_name: redis-api
    ports:
    - 6379:6379
  postgres:
    image: postgres
    container_name: postgres-api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=apidb
  api:
    build: .
    container_name: users-api
    volumes:
      - ".:/app"
    ports:
    - 5000:80
    depends_on:
      - redis
      - postgres
    command: >
      sh -c "
             flask api start-database &&
             flask api user-seed &&
             sh ./api-start.sh
            "