version: '3'
services:
  api:
    build: .
    container_name: users-api
    volumes:
      - ".:/app"
    ports:
    - 5000:5000
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    container_name: redis-api
    ports:
    - 6379:6379
  postgres:
    image: postgres
    ports:
      - 55002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw